# fly.toml app configuration file generated for idoriot on 2024-01-16T12:48:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "idoriot"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
